version: "3"

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.front
    ports:
      - "8000:8000"

    environment:
      - PORT=8000
      - NODE_ENV=dev
  redis:
    image: redis:7.2-alpine
    ports:
      - "6379:6379"
  #   depends_on:
  #     - postgres
  # postgres:
  #   image: postgres:16.2
  #   environment:
  #     POSTGRES_USER: night
  #     POSTGRES_PASSWORD: bomb
  #     POSTGRES_DB: colab
  #   ports:
  #     - "6000:5432"
