version: "3"

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.front
    ports:
      - "8000:8000"

    environment:
      - PORT=8000
      - NODE_ENV=dev
    depends_on:
      - postgres
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: night
      POSTGRES_PASSWORD: bomb
      POSTGRES_DB: colab
    ports:
      - "6000:5432"
