version: "3"

services:
  backend:
    image: nightstalker5699/backend
    ports:
      - "8000:8000"

  redis:
    image: redis:7.2-alpine
    ports:
      - "6379:6379"
  frontend:
    image: nightstalker5699/frontend
    ports:
      - "3000:3000"
