version: "3"

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      # - /app/node_modules
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: night
      POSTGRES_PASSWORD: bomb
      POSTGRES_DB: colab
    ports:
      - "5432:5432"
