version: "3"

volumes:
  node_modules:
services:
  backend:
    image: nightstalker5699/backend

  redis:
    image: redis:7.2-alpine
    ports:
      - "6379:6379"
  frontend:
    image: colab-backend-frontend:latest
    ports:
      - "3000:3000"
