version: "3"

volumes:
  node_modules:
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.prod
    ports:
      - "8000:8000"

  redis:
    image: redis:7.2-alpine
    ports:
      - "6379:6379"
  frontend:
    image: front/test
    ports:
      - "3000:3000"
