version: "3"

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      # - /app/node_modules
    environment:
      - PORT=8000
      - NODE_ENV=dev
    depends_on:
      - postgres
  postgres:
    image: postgres:16.2
    environment:
      POSTGRES_USER: night
      POSTGRES_PASSWORD: bomb
      POSTGRES_DB: colab
    ports:
      - "6000:5432"
