openapi: 3.0.3
info:
  title: Team Management API
  description: API for team management operations
  version: 1.0.0
  contact:
    name: API Support
    email: support@example.com

servers:
  - url: http://localhost:3000/api
    description: Development server
  - url: https://api.example.com
    description: Production server

tags:
  - name: Teams
    description: Team management operations

paths:
  /api/teams:
    get:
      tags:
        - Teams
      summary: Get my teams
      description: Retrieve all teams where the authenticated user is a member or leader
      security:
        - bearerAuth: []
      responses:
        "200":
          description: Teams retrieved successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: success
                  data:
                    type: array
                    items:
                      allOf:
                        - $ref: "#/components/schemas/Team"
                        - type: object
                          properties:
                            userRole:
                              type: string
                              enum: [LEADER, MEMBER]
                              example: "MEMBER"
                              description: Current user's role in this team
                            memberCount:
                              type: integer
                              example: 5
                              description: Total number of members in the team
              examples:
                success_response:
                  summary: Successful teams retrieval
                  value:
                    status: success
                    data:
                      - id: "team123"
                        teamName: "Development Team"
                        teamLogo: "https://example.com/logo.png"
                        theme: "blue"
                        joinCode: "ABC123XYZ"
                        userRole: "LEADER"
                        memberCount: 3
                        createdAt: "2024-01-15T10:30:00Z"
                        updatedAt: "2024-01-15T10:30:00Z"
                      - id: "team456"
                        teamName: "Marketing Team"
                        teamLogo: "https://example.com/marketing-logo.png"
                        theme: "green"
                        joinCode: "DEF456ABC"
                        userRole: "MEMBER"
                        memberCount: 7
                        createdAt: "2024-01-10T14:20:00Z"
                        updatedAt: "2024-01-12T09:15:00Z"
                empty_response:
                  summary: No teams found
                  value:
                    status: success
                    data: []
        "401":
          description: Unauthorized - Authentication required
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
              examples:
                unauthorized:
                  summary: Authentication required
                  value:
                    status: error
                    message: "Authentication required"
                    errorType: "AuthenticationError"
                    statusCode: 401
        "500":
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"

    post:
      tags:
        - Teams
      summary: Create a new team
      description: Create a new team with optional members. The authenticated user becomes the team leader.
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/CreateTeamRequest"
            examples:
              basic_team:
                summary: Basic team creation
                value:
                  teamData:
                    teamName: "Development Team"
                    teamLogo: "https://example.com/logo.png"
                    theme: "blue"
                  members: []
              team_with_members:
                summary: Team with initial members
                value:
                  teamData:
                    teamName: "Marketing Team"
                    teamLogo: "https://example.com/marketing-logo.png"
                    theme: "green"
                  members:
                    [
                      "2048691a-3c81-4f6f-b806-28c356daae93",
                      "bed92681-fd28-4801-8335-7fdaf45ce386",
                      "e2bea940-71f0-4ff5-9409-309c61ebcc12",
                    ]
      responses:
        "200":
          description: Team created successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: success
                  data:
                    $ref: "#/components/schemas/Team"
              examples:
                success_response:
                  summary: Successful team creation
                  value:
                    status: success
                    data:
                      id: "team123"
                      teamName: "Development Team"
                      teamLogo: "https://example.com/logo.png"
                      theme: "blue"
                      joinCode: "ABC123XYZ"
                      createdAt: "2024-01-15T10:30:00Z"
                      updatedAt: "2024-01-15T10:30:00Z"
        "400":
          description: Validation error - Team name is required
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
              examples:
                missing_team_name:
                  summary: Missing team name
                  value:
                    status: error
                    message: "you must insert a team"
                    errorType: "ValidationError"
                    statusCode: 400
                database_error:
                  summary: Database error
                  value:
                    status: error
                    message: "an error creating your team"
                    errorType: "DatabaseError"
                    statusCode: 400
        "401":
          description: Unauthorized - Authentication required
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
              examples:
                unauthorized:
                  summary: Authentication required
                  value:
                    status: error
                    message: "Authentication required"
                    errorType: "AuthenticationError"
                    statusCode: 401
        "500":
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
  /api/teams/joinTeam:
    post:
      summary: Join a team using a join code
      description: Allows an authenticated user to join an existing team by providing a valid join code
      tags:
        - Teams
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/JoinTeamRequest"
            examples:
              valid_request:
                summary: Valid join team request
                value:
                  joinCode: "ABC123XYZ0"
      responses:
        "200":
          description: Successfully joined the team
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/JoinTeamResponse"
              examples:
                success_response:
                  summary: Successful team join
                  value:
                    status: "sucess"
                    data:
                      team:
                        id: "team-uuid-123"
                        teamName: "Development Team"
                        joinCode: "ABC123XYZ0"
                        createdAt: "2024-01-15T10:30:00Z"
                        updatedAt: "2024-01-15T10:30:00Z"
                        userInTeams:
                          - user:
                              id: "user-uuid-456"
                              name: "John Doe"
                              email: "john@example.com"
                          - user:
                              id: "user-uuid-789"
                              name: "Jane Smith"
                              email: "jane@example.com"
        "400":
          description: Bad request - Missing or invalid join code
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
              examples:
                missing_code:
                  summary: Missing join code
                  value:
                    status: "error"
                    message: "you must input a code to join a team"
                    errorType: "ValidationError"
        "404":
          description: Team not found - Invalid join code
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
              examples:
                invalid_code:
                  summary: Invalid join code
                  value:
                    status: "error"
                    message: "This code doesn't belong to a team"
                    errorType: "ValidationError"
        "401":
          description: Unauthorized - Authentication required
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
        "500":
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
      description: JWT token for authentication

  schemas:
    CreateTeamRequest:
      type: object
      required:
        - teamData
      properties:
        teamData:
          type: object
          required:
            - teamName
          properties:
            teamName:
              type: string
              minLength: 1
              maxLength: 100
              example: "Development Team"
              description: The name of the team
            teamLogo:
              type: string
              format: uri
              example: "https://example.com/logo.png"
              description: URL to the team logo image
            theme:
              type: string
              example: "blue"
              description: Theme color for the team
        members:
          type: array
          items:
            type: string
          example: ["user1", "user2", "user3"]
          description: Array of user IDs to add as initial team members

    Team:
      type: object
      properties:
        id:
          type: string
          example: "team123"
          description: Unique identifier for the team
        teamName:
          type: string
          example: "Development Team"
          description: The name of the team
        teamLogo:
          type: string
          format: uri
          example: "https://example.com/logo.png"
          description: URL to the team logo image
        theme:
          type: string
          example: "blue"
          description: Theme color for the team
        joinCode:
          type: string
          example: "ABC123XYZ"
          description: Unique code for joining the team
        createdAt:
          type: string
          format: date-time
          example: "2024-01-15T10:30:00Z"
          description: Timestamp when the team was created
        updatedAt:
          type: string
          format: date-time
          example: "2024-01-15T10:30:00Z"
          description: Timestamp when the team was last updated

    UserInTeam:
      type: object
      properties:
        id:
          type: string
          example: "relation123"
          description: Unique identifier for the user-team relationship
        userId:
          type: string
          example: "user123"
          description: ID of the user
        teamId:
          type: string
          example: "team123"
          description: ID of the team
        role:
          type: string
          enum: [LEADER, MEMBER]
          example: "MEMBER"
          description: Role of the user in the team
        createdAt:
          type: string
          format: date-time
          example: "2024-01-15T10:30:00Z"
          description: Timestamp when the user joined the team
        updatedAt:
          type: string
          format: date-time
          example: "2024-01-15T10:30:00Z"
          description: Timestamp when the relationship was last updated

    Error:
      type: object
      properties:
        status:
          type: string
          example: error
          description: Status of the response
        message:
          type: string
          example: "An error occurred"
          description: Human-readable error message
        errorType:
          type: string
          example: "ValidationError"
          description: Type of error that occurred
        statusCode:
          type: integer
          example: 400
          description: HTTP status code
